### ISSUE TITLE
Service changes

### ISSUE THREAD

**Issue by Snazzah** [dbots-pkg/dbots.js#58] opened 2020-10-11 18:42 UTC
The list of changes is in this project: https://github.com/dbots-pkg/dbots.js/projects/2

**Comment by EndBug** [comment] 2020-10-16 10:43
https://infinitybots.xyz/ Can't be reached
https://disbots.gg/ Is currently responding with a 521 from Cloudflare

If you're in their support guilds, do you have any info?

**Comment by Snazzah** [comment] 2020-10-16 13:01
I didn't join their guilds yet, I had the sites down for later. They were online before, maybe wait a couple of days to see if they come back up and then I could get more info.

**Comment by EndBug** [comment] 2020-10-20 18:12
They're still unavailable: I'll add AstroBotList in the meanwhile, let me know if you find out something.

**Comment by Snazzah** [comment] 2020-10-21 21:38
Since both https://infinitybots.xyz/ and https://disbots.gg/ suddenly died and I found some other lists to add, I'm just going to update this issue with the new lists. #62 won't close this issue, but I can mark it off from the description.

**Comment by Snazzah** [comment] 2020-10-24 18:46
Adding one more botlist to this issue, not sure if we previously removed BladeBotList before.

**Comment by EndBug** [comment] 2020-10-24 19:01
FYI: I'm stalling on this a little bit, because I'm trying to see if we can switch to TypeScript without messing up with our current docs generator. I don't have a lot of time and it seems to be somewhat complex, so sorry if I'm taking so long 🙏🏻

**Comment by Snazzah** [comment] 2020-10-24 19:58
Thats fine, I was thinking of moving to TypeScript anyways.

**Comment by EndBug** [comment] 2021-01-05 14:34
FYI: https://infinitybots.xyz was the previous URL of https://infinitybotlist.com, I've had the confirmation form one of the staff members
I've replaced the old website with the new one

**Comment by EndBug** [comment] 2021-01-05 14:43
@Snazzah Are you in the DisTop server? I've tried entering it but it's like I don't have permission to see any channel at all, not even the one from the invite

**Comment by EndBug** [comment] 2021-01-05 14:45
https://botsbase.net/ Times out, are you also in their support guild?

**Comment by Snazzah** [comment] 2021-01-05 14:46
@EndBug server is empty for some reason, would probably assume its closing later

**Comment by EndBug** [comment] 2021-01-05 14:50
> @EndBug server is empty for some reason, would probably assume its closing later

BotsBase or DisTop?

**Comment by EndBug** [comment] 2021-01-05 15:43
Update: DisTop has re-appeared

**Comment by Snazzah** [comment] 2021-01-05 19:34
> BotsBase or DisTop?

I was talking about DisTop, didn't see the next comment

**Comment by EndBug** [comment] 2021-01-07 15:18
GlennBotList is dead, am I right?

**Comment by Snazzah** [comment] 2021-01-07 16:03
@EndBug Yep, the site https://glennbotlist.xyz/ redirects to a VoidBots bot page to redirect traffic.

**Comment by EndBug** [comment] 2021-01-07 17:07
Yeah, LBots has confirmed that the service is dead on the Discord guild

GlennBotList says that they're temporarily closed, but they will come back in the future... Should we remove them and re-add them in the future, or just keep them for the time being?

**Comment by Snazzah** [comment] 2021-01-07 20:06
Probably leave them in then.

**Comment by EndBug** [comment] 2021-01-13 20:08
Apparently, VoidBots needs to be re-added since they're going to update their API from Jan 25th.
Docs are still at the same address

**Comment by EndBug** [comment] 2021-01-17 13:47
FYI: botsbase.net is now owned by bots.land, which should release their API soon

**Comment by EndBug** [comment] 2021-02-20 15:32
Idledev (former Mythical Bots) is unreachable, are you in their guild?

**Comment by Snazzah** [comment] 2021-02-21 05:03
No, not in their guild.

**Comment by EndBug** [comment] 2021-02-21 09:46
I guess I'll just remove Mythical Bots, we'll re-add Idle Dev if they start working again

**Comment by EndBug** [comment] 2021-02-25 19:56
@Snazzah Do you know anything about DisTop? It seems like they just disappeared...

**Comment by Snazzah** [comment] 2021-02-25 20:04
Not sure what happened.

**Comment by EndBug** [comment] 2021-04-05 12:42
Hey @Snazzah, I was thinking about considering changes to list class names as not breaking changes. After all, we provide a method to get a service class using its alias (`Service.get`), so we should encourage people to use that instead of relying on internal class names. I could add an example that shows how to do that, and maybe remove `serviceClasses` from the exported variables (users can still get that through `Service.getAll()`, but this way they'll be encouraged not to rely on that unless they really need every class)
What do you think?

**Comment by Snazzah** [comment] 2021-04-05 12:45
@EndBug, sounds good to me. May also need to have to be reflected in the docs since this still shows for every class exposed:
![](https://get.snaz.in/9qp6WxH.png)

**Comment by EndBug** [comment] 2021-04-05 12:47
Hmm right. I'm not sure what generates that snippet, but I'll look into it

**Comment by EndBug** [comment] 2021-04-05 13:01
@Snazzah That example is created by the website itself. I think we can replace it with something like this: 

![image](https://user-images.githubusercontent.com/26386270/113576311-a1f0d680-961f-11eb-820a-11763d1e19db.png)

I'll also change the `dbots.ClassName` in the services file

**Comment by EndBug** [comment] 2022-01-19 17:57
I'm moving the service changes tracking to the new projects: https://github.com/orgs/dbots-pkg/projects/2/views/9

This type of project is issue-based, so that will allow us to better track the date of the proposal and the conversations about list changes.

The previous project has been closed, and I'm going to close this issue as well

**Closed by EndBug** 2022-01-19 17:57 UTC
Labels: type: feature, status: pinned
